title: SOAL Cluster Docs
description: Documentation, policies, and tips for using and administrating the Stanford MS&E SOAL Cluster.
theme: just-the-docs

url: https://soal-cluster.github.io/

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/soal-cluster/soal-cluster.github.io
